// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: e2e/v1/e2e.proto

package pb

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/datachainlab/ethereum-light-client-types/prover/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VerifyUpdateRequest struct {
	// ------ chain / client config ------
	SyncCommitteeSize            uint32                `protobuf:"varint,1,opt,name=sync_committee_size,json=syncCommitteeSize,proto3" json:"sync_committee_size,omitempty"`
	GenesisValidatorsRoot        []byte                `protobuf:"bytes,2,opt,name=genesis_validators_root,json=genesisValidatorsRoot,proto3" json:"genesis_validators_root,omitempty"`
	MinSyncCommitteeParticipants uint64                `protobuf:"varint,3,opt,name=min_sync_committee_participants,json=minSyncCommitteeParticipants,proto3" json:"min_sync_committee_participants,omitempty"`
	GenesisTime                  uint64                `protobuf:"varint,4,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	ForkParameters               *types.ForkParameters `protobuf:"bytes,5,opt,name=fork_parameters,json=forkParameters,proto3" json:"fork_parameters,omitempty"`
	SecondsPerSlot               uint64                `protobuf:"varint,6,opt,name=seconds_per_slot,json=secondsPerSlot,proto3" json:"seconds_per_slot,omitempty"`
	SlotsPerEpoch                uint64                `protobuf:"varint,7,opt,name=slots_per_epoch,json=slotsPerEpoch,proto3" json:"slots_per_epoch,omitempty"`
	EpochsPerSyncCommitteePeriod uint64                `protobuf:"varint,8,opt,name=epochs_per_sync_committee_period,json=epochsPerSyncCommitteePeriod,proto3" json:"epochs_per_sync_committee_period,omitempty"`
	TrustLevelNumerator          uint64                `protobuf:"varint,9,opt,name=trust_level_numerator,json=trustLevelNumerator,proto3" json:"trust_level_numerator,omitempty"`
	TrustLevelDenominator        uint64                `protobuf:"varint,10,opt,name=trust_level_denominator,json=trustLevelDenominator,proto3" json:"trust_level_denominator,omitempty"`
	TrustingPeriodSecs           uint64                `protobuf:"varint,11,opt,name=trusting_period_secs,json=trustingPeriodSecs,proto3" json:"trusting_period_secs,omitempty"`
	MaxClockDriftSecs            uint64                `protobuf:"varint,12,opt,name=max_clock_drift_secs,json=maxClockDriftSecs,proto3" json:"max_clock_drift_secs,omitempty"`
	IbcAddress                   []byte                `protobuf:"bytes,13,opt,name=ibc_address,json=ibcAddress,proto3" json:"ibc_address,omitempty"`
	// ------ trusted consensus state ------
	// trusted_height.revision_height carries the trusted beacon slot
	TrustedSyncCommittee        *types.TrustedSyncCommittee `protobuf:"bytes,14,opt,name=trusted_sync_committee,json=trustedSyncCommittee,proto3" json:"trusted_sync_committee,omitempty"`
	TrustedCurrentSyncCommittee []byte                      `protobuf:"bytes,15,opt,name=trusted_current_sync_committee,json=trustedCurrentSyncCommittee,proto3" json:"trusted_current_sync_committee,omitempty"`
	TrustedNextSyncCommittee    []byte                      `protobuf:"bytes,16,opt,name=trusted_next_sync_committee,json=trustedNextSyncCommittee,proto3" json:"trusted_next_sync_committee,omitempty"`
	TrustedTimestampSecs        uint64                      `protobuf:"varint,17,opt,name=trusted_timestamp_secs,json=trustedTimestampSecs,proto3" json:"trusted_timestamp_secs,omitempty"`
	// ------ header ------
	ConsensusUpdate     *types.ConsensusUpdate `protobuf:"bytes,18,opt,name=consensus_update,json=consensusUpdate,proto3" json:"consensus_update,omitempty"`
	ExecutionUpdate     *types.ExecutionUpdate `protobuf:"bytes,19,opt,name=execution_update,json=executionUpdate,proto3" json:"execution_update,omitempty"`
	AccountUpdate       *types.AccountUpdate   `protobuf:"bytes,20,opt,name=account_update,json=accountUpdate,proto3" json:"account_update,omitempty"`
	HeaderTimestampSecs uint64                 `protobuf:"varint,21,opt,name=header_timestamp_secs,json=headerTimestampSecs,proto3" json:"header_timestamp_secs,omitempty"`
	// ------ host ------
	NowSecs uint64 `protobuf:"varint,22,opt,name=now_secs,json=nowSecs,proto3" json:"now_secs,omitempty"`
	// ------ membership verification (optional; skipped when path is empty) ------
	IbcCommitmentsSlot []byte `protobuf:"bytes,23,opt,name=ibc_commitments_slot,json=ibcCommitmentsSlot,proto3" json:"ibc_commitments_slot,omitempty"`
	MembershipPath     string `protobuf:"bytes,24,opt,name=membership_path,json=membershipPath,proto3" json:"membership_path,omitempty"`
	MembershipValue    []byte `protobuf:"bytes,25,opt,name=membership_value,json=membershipValue,proto3" json:"membership_value,omitempty"`
	MembershipProof    []byte `protobuf:"bytes,26,opt,name=membership_proof,json=membershipProof,proto3" json:"membership_proof,omitempty"`
}

func (m *VerifyUpdateRequest) Reset()         { *m = VerifyUpdateRequest{} }
func (m *VerifyUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyUpdateRequest) ProtoMessage()    {}
func (*VerifyUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f28696dd104c32, []int{0}
}
func (m *VerifyUpdateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyUpdateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifyUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUpdateRequest.Merge(m, src)
}
func (m *VerifyUpdateRequest) XXX_Size() int {
	return m.Size()
}
func (m *VerifyUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUpdateRequest proto.InternalMessageInfo

func (m *VerifyUpdateRequest) GetSyncCommitteeSize() uint32 {
	if m != nil {
		return m.SyncCommitteeSize
	}
	return 0
}

func (m *VerifyUpdateRequest) GetGenesisValidatorsRoot() []byte {
	if m != nil {
		return m.GenesisValidatorsRoot
	}
	return nil
}

func (m *VerifyUpdateRequest) GetMinSyncCommitteeParticipants() uint64 {
	if m != nil {
		return m.MinSyncCommitteeParticipants
	}
	return 0
}

func (m *VerifyUpdateRequest) GetGenesisTime() uint64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

func (m *VerifyUpdateRequest) GetForkParameters() *types.ForkParameters {
	if m != nil {
		return m.ForkParameters
	}
	return nil
}

func (m *VerifyUpdateRequest) GetSecondsPerSlot() uint64 {
	if m != nil {
		return m.SecondsPerSlot
	}
	return 0
}

func (m *VerifyUpdateRequest) GetSlotsPerEpoch() uint64 {
	if m != nil {
		return m.SlotsPerEpoch
	}
	return 0
}

func (m *VerifyUpdateRequest) GetEpochsPerSyncCommitteePeriod() uint64 {
	if m != nil {
		return m.EpochsPerSyncCommitteePeriod
	}
	return 0
}

func (m *VerifyUpdateRequest) GetTrustLevelNumerator() uint64 {
	if m != nil {
		return m.TrustLevelNumerator
	}
	return 0
}

func (m *VerifyUpdateRequest) GetTrustLevelDenominator() uint64 {
	if m != nil {
		return m.TrustLevelDenominator
	}
	return 0
}

func (m *VerifyUpdateRequest) GetTrustingPeriodSecs() uint64 {
	if m != nil {
		return m.TrustingPeriodSecs
	}
	return 0
}

func (m *VerifyUpdateRequest) GetMaxClockDriftSecs() uint64 {
	if m != nil {
		return m.MaxClockDriftSecs
	}
	return 0
}

func (m *VerifyUpdateRequest) GetIbcAddress() []byte {
	if m != nil {
		return m.IbcAddress
	}
	return nil
}

func (m *VerifyUpdateRequest) GetTrustedSyncCommittee() *types.TrustedSyncCommittee {
	if m != nil {
		return m.TrustedSyncCommittee
	}
	return nil
}

func (m *VerifyUpdateRequest) GetTrustedCurrentSyncCommittee() []byte {
	if m != nil {
		return m.TrustedCurrentSyncCommittee
	}
	return nil
}

func (m *VerifyUpdateRequest) GetTrustedNextSyncCommittee() []byte {
	if m != nil {
		return m.TrustedNextSyncCommittee
	}
	return nil
}

func (m *VerifyUpdateRequest) GetTrustedTimestampSecs() uint64 {
	if m != nil {
		return m.TrustedTimestampSecs
	}
	return 0
}

func (m *VerifyUpdateRequest) GetConsensusUpdate() *types.ConsensusUpdate {
	if m != nil {
		return m.ConsensusUpdate
	}
	return nil
}

func (m *VerifyUpdateRequest) GetExecutionUpdate() *types.ExecutionUpdate {
	if m != nil {
		return m.ExecutionUpdate
	}
	return nil
}

func (m *VerifyUpdateRequest) GetAccountUpdate() *types.AccountUpdate {
	if m != nil {
		return m.AccountUpdate
	}
	return nil
}

func (m *VerifyUpdateRequest) GetHeaderTimestampSecs() uint64 {
	if m != nil {
		return m.HeaderTimestampSecs
	}
	return 0
}

func (m *VerifyUpdateRequest) GetNowSecs() uint64 {
	if m != nil {
		return m.NowSecs
	}
	return 0
}

func (m *VerifyUpdateRequest) GetIbcCommitmentsSlot() []byte {
	if m != nil {
		return m.IbcCommitmentsSlot
	}
	return nil
}

func (m *VerifyUpdateRequest) GetMembershipPath() string {
	if m != nil {
		return m.MembershipPath
	}
	return ""
}

func (m *VerifyUpdateRequest) GetMembershipValue() []byte {
	if m != nil {
		return m.MembershipValue
	}
	return nil
}

func (m *VerifyUpdateRequest) GetMembershipProof() []byte {
	if m != nil {
		return m.MembershipProof
	}
	return nil
}

type VerifyUpdateResponse struct {
	// aggregate pubkeys of the sync committees after applying the update
	CurrentSyncCommittee []byte `protobuf:"bytes,1,opt,name=current_sync_committee,json=currentSyncCommittee,proto3" json:"current_sync_committee,omitempty"`
	NextSyncCommittee    []byte `protobuf:"bytes,2,opt,name=next_sync_committee,json=nextSyncCommittee,proto3" json:"next_sync_committee,omitempty"`
}

func (m *VerifyUpdateResponse) Reset()         { *m = VerifyUpdateResponse{} }
func (m *VerifyUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyUpdateResponse) ProtoMessage()    {}
func (*VerifyUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f28696dd104c32, []int{1}
}
func (m *VerifyUpdateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyUpdateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifyUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUpdateResponse.Merge(m, src)
}
func (m *VerifyUpdateResponse) XXX_Size() int {
	return m.Size()
}
func (m *VerifyUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUpdateResponse proto.InternalMessageInfo

func (m *VerifyUpdateResponse) GetCurrentSyncCommittee() []byte {
	if m != nil {
		return m.CurrentSyncCommittee
	}
	return nil
}

func (m *VerifyUpdateResponse) GetNextSyncCommittee() []byte {
	if m != nil {
		return m.NextSyncCommittee
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifyUpdateRequest)(nil), "e2e.v1.VerifyUpdateRequest")
	proto.RegisterType((*VerifyUpdateResponse)(nil), "e2e.v1.VerifyUpdateResponse")
}

func init() { proto.RegisterFile("e2e/v1/e2e.proto", fileDescriptor_69f28696dd104c32) }

var fileDescriptor_69f28696dd104c32 = []byte{
	// 889 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0xdb, 0xb6,
	0x1b, 0x8f, 0xfe, 0xff, 0x2e, 0x4d, 0xe9, 0xc4, 0x76, 0x68, 0xa7, 0x55, 0xd3, 0xc2, 0xf5, 0x7a,
	0xd8, 0x3c, 0x74, 0x91, 0x1b, 0x6f, 0xd8, 0x6d, 0x87, 0xcc, 0x4d, 0x81, 0x01, 0x43, 0x61, 0x38,
	0x2f, 0x18, 0xb6, 0x83, 0x40, 0x51, 0x8f, 0x23, 0x22, 0x12, 0xa9, 0x91, 0x94, 0xeb, 0x14, 0xfb,
	0x10, 0xfb, 0x58, 0x3b, 0xf6, 0xb8, 0xe3, 0x90, 0x7c, 0x85, 0x7d, 0x80, 0x81, 0xa4, 0x94, 0xd8,
	0x9a, 0x17, 0xec, 0x66, 0x3d, 0xbf, 0x97, 0x87, 0xfe, 0xf1, 0x21, 0x89, 0xda, 0x30, 0x82, 0xe1,
	0xfc, 0x70, 0x08, 0x23, 0x08, 0x72, 0x29, 0xb4, 0xc0, 0x9b, 0xe6, 0xe7, 0xfc, 0x70, 0xff, 0x15,
	0x8b, 0xe8, 0x30, 0x65, 0x17, 0x89, 0xa6, 0x29, 0x03, 0xae, 0xd5, 0x10, 0x74, 0x02, 0x12, 0x8a,
	0xcc, 0xf2, 0xcb, 0xdf, 0x4e, 0xf4, 0xf2, 0xaf, 0x06, 0xea, 0x9c, 0x83, 0x64, 0xb3, 0xab, 0xb3,
	0x3c, 0x26, 0x1a, 0xa6, 0xf0, 0x4b, 0x01, 0x4a, 0xe3, 0x00, 0x75, 0xd4, 0x15, 0xa7, 0x21, 0x15,
	0x59, 0xc6, 0xb4, 0x06, 0x08, 0x15, 0xfb, 0x00, 0xbe, 0xd7, 0xf7, 0x06, 0x3b, 0xd3, 0x5d, 0x03,
	0x8d, 0x2b, 0xe4, 0x84, 0x7d, 0x00, 0xfc, 0x0d, 0x7a, 0x72, 0x01, 0x1c, 0x14, 0x53, 0xe1, 0x9c,
	0xa4, 0x2c, 0x26, 0x5a, 0x48, 0x15, 0x4a, 0x21, 0xb4, 0xff, 0xbf, 0xbe, 0x37, 0xd8, 0x9e, 0xee,
	0x95, 0xf0, 0xf9, 0x2d, 0x3a, 0x15, 0x42, 0xe3, 0x63, 0xf4, 0x22, 0x63, 0x3c, 0xac, 0xf5, 0xca,
	0x89, 0xd4, 0x8c, 0xb2, 0x9c, 0x70, 0xad, 0xfc, 0xff, 0xf7, 0xbd, 0xc1, 0x83, 0xe9, 0xf3, 0x8c,
	0xf1, 0x93, 0xe5, 0xb6, 0x93, 0x25, 0x0e, 0xfe, 0x14, 0x6d, 0x57, 0xed, 0x35, 0xcb, 0xc0, 0x7f,
	0x60, 0x35, 0x8d, 0xb2, 0x76, 0xca, 0x32, 0xc0, 0x67, 0xa8, 0x35, 0x13, 0xf2, 0xd2, 0x78, 0x93,
	0x0c, 0x34, 0x48, 0xe5, 0x7f, 0xd2, 0xf7, 0x06, 0x8d, 0xd1, 0x97, 0x01, 0x8b, 0x68, 0xb0, 0x1c,
	0x58, 0x70, 0x1b, 0xd2, 0xfc, 0x30, 0x78, 0x2b, 0xe4, 0xe5, 0xe4, 0x56, 0x33, 0x6d, 0xce, 0x56,
	0xbe, 0xf1, 0x00, 0xb5, 0x15, 0x50, 0xc1, 0x63, 0x15, 0xe6, 0x20, 0x43, 0x95, 0x0a, 0xed, 0x6f,
	0xda, 0xee, 0xcd, 0xb2, 0x3e, 0x01, 0x79, 0x92, 0x0a, 0x8d, 0x3f, 0x43, 0x2d, 0x83, 0x3a, 0x1e,
	0xe4, 0x82, 0x26, 0xfe, 0x43, 0x4b, 0xdc, 0xb1, 0xe5, 0x09, 0xc8, 0x63, 0x53, 0xc4, 0x6f, 0x51,
	0xdf, 0xa2, 0xa5, 0x61, 0x2d, 0x19, 0x90, 0x4c, 0xc4, 0xfe, 0x96, 0xcb, 0xc4, 0xf1, 0x4c, 0x83,
	0x95, 0x64, 0x2c, 0x07, 0x8f, 0xd0, 0x9e, 0x96, 0x85, 0xd2, 0x61, 0x0a, 0x73, 0x48, 0x43, 0x5e,
	0x64, 0x20, 0x4d, 0xf0, 0xfe, 0x23, 0x2b, 0xee, 0x58, 0xf0, 0x07, 0x83, 0xbd, 0xab, 0x20, 0xb3,
	0x8d, 0xcb, 0x9a, 0x18, 0xb8, 0xc8, 0x18, 0xb7, 0x2a, 0x64, 0x55, 0x7b, 0x77, 0xaa, 0x37, 0x77,
	0x20, 0x7e, 0x8d, 0xba, 0x16, 0x60, 0xfc, 0xa2, 0x5c, 0x62, 0xa8, 0x80, 0x2a, 0xbf, 0x61, 0x45,
	0xb8, 0xc2, 0xdc, 0xca, 0x4e, 0x80, 0x2a, 0x3c, 0x44, 0xdd, 0x8c, 0x2c, 0x42, 0x9a, 0x0a, 0x7a,
	0x19, 0xc6, 0x92, 0xcd, 0xb4, 0x53, 0x6c, 0x5b, 0xc5, 0x6e, 0x46, 0x16, 0x63, 0x03, 0xbd, 0x31,
	0x88, 0x15, 0xbc, 0x40, 0x0d, 0x16, 0xd1, 0x90, 0xc4, 0xb1, 0x04, 0xa5, 0xfc, 0x1d, 0x3b, 0x55,
	0x88, 0x45, 0xf4, 0xc8, 0x55, 0x70, 0x82, 0x1e, 0xdb, 0x3e, 0x10, 0xd7, 0x42, 0xf3, 0x9b, 0x76,
	0x9f, 0x47, 0xf7, 0xef, 0xf3, 0xa9, 0xd3, 0xae, 0x24, 0x39, 0xed, 0xea, 0x35, 0x55, 0x3c, 0x46,
	0xbd, 0xaa, 0x13, 0x2d, 0xa4, 0x04, 0xae, 0xeb, 0x1d, 0x5b, 0x76, 0x75, 0xcf, 0x4a, 0xd6, 0xd8,
	0x91, 0x56, 0x4d, 0xbe, 0x45, 0x15, 0x1c, 0x72, 0x58, 0xfc, 0xc3, 0xa1, 0x6d, 0x1d, 0xfc, 0x92,
	0xf2, 0x0e, 0x16, 0x35, 0xf9, 0xd7, 0x77, 0xff, 0xd6, 0x4c, 0xbc, 0xd2, 0x24, 0xcb, 0x5d, 0x82,
	0xbb, 0x36, 0xc1, 0x6a, 0xe5, 0xa7, 0x15, 0x68, 0x43, 0xfc, 0x11, 0xb5, 0xa9, 0xe0, 0x0a, 0xb8,
	0x2a, 0x54, 0x58, 0xd8, 0x13, 0xef, 0x63, 0x9b, 0xce, 0xc1, 0xfd, 0xe9, 0x8c, 0x2b, 0x55, 0x79,
	0x4d, 0xb4, 0xe8, 0x6a, 0xc1, 0x38, 0xc3, 0x02, 0x68, 0xa1, 0x99, 0xe0, 0x95, 0x73, 0xe7, 0xbf,
	0x38, 0x1f, 0x57, 0xaa, 0xca, 0x19, 0x56, 0x0b, 0x78, 0x8a, 0x9a, 0x84, 0x52, 0x51, 0x70, 0x5d,
	0xf9, 0x76, 0xad, 0xef, 0xab, 0xfb, 0x7d, 0x8f, 0x9c, 0xa6, 0x74, 0xdd, 0x21, 0xcb, 0x9f, 0xe6,
	0x6c, 0x24, 0x40, 0x62, 0x90, 0xf5, 0xf0, 0xf6, 0xdc, 0xd9, 0x70, 0xe0, 0x6a, 0x76, 0x4f, 0xd1,
	0x16, 0x17, 0xef, 0x1d, 0xed, 0xb1, 0xa5, 0x3d, 0xe4, 0xe2, 0xbd, 0x85, 0x5e, 0xa3, 0xae, 0x99,
	0x4d, 0xb7, 0x7b, 0x99, 0x59, 0x8a, 0xbb, 0x08, 0x9e, 0xd8, 0x4d, 0xc4, 0x2c, 0x2a, 0x37, 0xce,
	0x42, 0xf6, 0x32, 0xf8, 0x1c, 0xb5, 0x32, 0xc8, 0x22, 0x90, 0x2a, 0x61, 0x79, 0x98, 0x13, 0x9d,
	0xf8, 0x7e, 0xdf, 0x1b, 0x3c, 0x9a, 0x36, 0xef, 0xca, 0x13, 0xa2, 0x13, 0xfc, 0x05, 0x6a, 0x2f,
	0x11, 0xe7, 0x24, 0x2d, 0xc0, 0x7f, 0x6a, 0x6d, 0x97, 0x0c, 0xce, 0x4d, 0xb9, 0x46, 0xcd, 0xa5,
	0x10, 0x33, 0x7f, 0xbf, 0x4e, 0x9d, 0x98, 0xf2, 0xcb, 0x5f, 0x51, 0x77, 0xf5, 0xd6, 0x57, 0xb9,
	0xd9, 0x4f, 0x33, 0x55, 0xff, 0x32, 0xd1, 0x9e, 0x35, 0xea, 0xd2, 0x75, 0xa3, 0x1c, 0xa0, 0xce,
	0xba, 0x11, 0x76, 0x17, 0xff, 0x2e, 0xaf, 0xcf, 0xee, 0xe8, 0x0c, 0x6d, 0xd9, 0xee, 0x0c, 0x24,
	0xfe, 0x1e, 0x6d, 0x2f, 0xaf, 0x04, 0x3f, 0x0b, 0xdc, 0x33, 0x16, 0xac, 0x79, 0x95, 0xf6, 0x9f,
	0xaf, 0x07, 0xdd, 0xe2, 0xbf, 0xfb, 0xf9, 0xf7, 0xeb, 0x9e, 0xf7, 0xf1, 0xba, 0xe7, 0xfd, 0x79,
	0xdd, 0xf3, 0x7e, 0xbb, 0xe9, 0x6d, 0x7c, 0xbc, 0xe9, 0x6d, 0xfc, 0x71, 0xd3, 0xdb, 0xf8, 0xe9,
	0xe8, 0x82, 0xe9, 0xa4, 0x88, 0x02, 0x2a, 0xb2, 0x61, 0x4c, 0x34, 0xa1, 0x09, 0x61, 0x3c, 0x25,
	0xd1, 0xed, 0x6b, 0x78, 0x60, 0xc7, 0xe8, 0xc0, 0xcd, 0xd1, 0x81, 0xbe, 0xca, 0x41, 0x99, 0x97,
	0x75, 0xe8, 0x0a, 0xc3, 0x3c, 0x8a, 0x36, 0xed, 0x7b, 0xf9, 0xd5, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x31, 0x32, 0xfb, 0x12, 0x78, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifierClient interface {
	VerifyUpdate(ctx context.Context, in *VerifyUpdateRequest, opts ...grpc.CallOption) (*VerifyUpdateResponse, error)
}

type verifierClient struct {
	cc grpc1.ClientConn
}

func NewVerifierClient(cc grpc1.ClientConn) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) VerifyUpdate(ctx context.Context, in *VerifyUpdateRequest, opts ...grpc.CallOption) (*VerifyUpdateResponse, error) {
	out := new(VerifyUpdateResponse)
	err := c.cc.Invoke(ctx, "/e2e.v1.Verifier/VerifyUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
type VerifierServer interface {
	VerifyUpdate(context.Context, *VerifyUpdateRequest) (*VerifyUpdateResponse, error)
}

// UnimplementedVerifierServer can be embedded to have forward compatible implementations.
type UnimplementedVerifierServer struct {
}

func (*UnimplementedVerifierServer) VerifyUpdate(ctx context.Context, req *VerifyUpdateRequest) (*VerifyUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUpdate not implemented")
}

func RegisterVerifierServer(s grpc1.Server, srv VerifierServer) {
	s.RegisterService(&_Verifier_serviceDesc, srv)
}

func _Verifier_VerifyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).VerifyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/e2e.v1.Verifier/VerifyUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).VerifyUpdate(ctx, req.(*VerifyUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Verifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "e2e.v1.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyUpdate",
			Handler:    _Verifier_VerifyUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "e2e/v1/e2e.proto",
}

func (m *VerifyUpdateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyUpdateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifyUpdateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MembershipProof) > 0 {
		i -= len(m.MembershipProof)
		copy(dAtA[i:], m.MembershipProof)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.MembershipProof)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd2
	}
	if len(m.MembershipValue) > 0 {
		i -= len(m.MembershipValue)
		copy(dAtA[i:], m.MembershipValue)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.MembershipValue)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if len(m.MembershipPath) > 0 {
		i -= len(m.MembershipPath)
		copy(dAtA[i:], m.MembershipPath)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.MembershipPath)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if len(m.IbcCommitmentsSlot) > 0 {
		i -= len(m.IbcCommitmentsSlot)
		copy(dAtA[i:], m.IbcCommitmentsSlot)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.IbcCommitmentsSlot)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if m.NowSecs != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.NowSecs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.HeaderTimestampSecs != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.HeaderTimestampSecs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.AccountUpdate != nil {
		{
			size, err := m.AccountUpdate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintE2E(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.ExecutionUpdate != nil {
		{
			size, err := m.ExecutionUpdate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintE2E(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.ConsensusUpdate != nil {
		{
			size, err := m.ConsensusUpdate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintE2E(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.TrustedTimestampSecs != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.TrustedTimestampSecs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.TrustedNextSyncCommittee) > 0 {
		i -= len(m.TrustedNextSyncCommittee)
		copy(dAtA[i:], m.TrustedNextSyncCommittee)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.TrustedNextSyncCommittee)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.TrustedCurrentSyncCommittee) > 0 {
		i -= len(m.TrustedCurrentSyncCommittee)
		copy(dAtA[i:], m.TrustedCurrentSyncCommittee)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.TrustedCurrentSyncCommittee)))
		i--
		dAtA[i] = 0x7a
	}
	if m.TrustedSyncCommittee != nil {
		{
			size, err := m.TrustedSyncCommittee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintE2E(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	if len(m.IbcAddress) > 0 {
		i -= len(m.IbcAddress)
		copy(dAtA[i:], m.IbcAddress)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.IbcAddress)))
		i--
		dAtA[i] = 0x6a
	}
	if m.MaxClockDriftSecs != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.MaxClockDriftSecs))
		i--
		dAtA[i] = 0x60
	}
	if m.TrustingPeriodSecs != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.TrustingPeriodSecs))
		i--
		dAtA[i] = 0x58
	}
	if m.TrustLevelDenominator != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.TrustLevelDenominator))
		i--
		dAtA[i] = 0x50
	}
	if m.TrustLevelNumerator != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.TrustLevelNumerator))
		i--
		dAtA[i] = 0x48
	}
	if m.EpochsPerSyncCommitteePeriod != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.EpochsPerSyncCommitteePeriod))
		i--
		dAtA[i] = 0x40
	}
	if m.SlotsPerEpoch != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.SlotsPerEpoch))
		i--
		dAtA[i] = 0x38
	}
	if m.SecondsPerSlot != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.SecondsPerSlot))
		i--
		dAtA[i] = 0x30
	}
	if m.ForkParameters != nil {
		{
			size, err := m.ForkParameters.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintE2E(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.GenesisTime != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.GenesisTime))
		i--
		dAtA[i] = 0x20
	}
	if m.MinSyncCommitteeParticipants != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.MinSyncCommitteeParticipants))
		i--
		dAtA[i] = 0x18
	}
	if len(m.GenesisValidatorsRoot) > 0 {
		i -= len(m.GenesisValidatorsRoot)
		copy(dAtA[i:], m.GenesisValidatorsRoot)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.GenesisValidatorsRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.SyncCommitteeSize != 0 {
		i = encodeVarintE2E(dAtA, i, uint64(m.SyncCommitteeSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VerifyUpdateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyUpdateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifyUpdateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NextSyncCommittee) > 0 {
		i -= len(m.NextSyncCommittee)
		copy(dAtA[i:], m.NextSyncCommittee)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.NextSyncCommittee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CurrentSyncCommittee) > 0 {
		i -= len(m.CurrentSyncCommittee)
		copy(dAtA[i:], m.CurrentSyncCommittee)
		i = encodeVarintE2E(dAtA, i, uint64(len(m.CurrentSyncCommittee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintE2E(dAtA []byte, offset int, v uint64) int {
	offset -= sovE2E(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VerifyUpdateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SyncCommitteeSize != 0 {
		n += 1 + sovE2E(uint64(m.SyncCommitteeSize))
	}
	l = len(m.GenesisValidatorsRoot)
	if l > 0 {
		n += 1 + l + sovE2E(uint64(l))
	}
	if m.MinSyncCommitteeParticipants != 0 {
		n += 1 + sovE2E(uint64(m.MinSyncCommitteeParticipants))
	}
	if m.GenesisTime != 0 {
		n += 1 + sovE2E(uint64(m.GenesisTime))
	}
	if m.ForkParameters != nil {
		l = m.ForkParameters.Size()
		n += 1 + l + sovE2E(uint64(l))
	}
	if m.SecondsPerSlot != 0 {
		n += 1 + sovE2E(uint64(m.SecondsPerSlot))
	}
	if m.SlotsPerEpoch != 0 {
		n += 1 + sovE2E(uint64(m.SlotsPerEpoch))
	}
	if m.EpochsPerSyncCommitteePeriod != 0 {
		n += 1 + sovE2E(uint64(m.EpochsPerSyncCommitteePeriod))
	}
	if m.TrustLevelNumerator != 0 {
		n += 1 + sovE2E(uint64(m.TrustLevelNumerator))
	}
	if m.TrustLevelDenominator != 0 {
		n += 1 + sovE2E(uint64(m.TrustLevelDenominator))
	}
	if m.TrustingPeriodSecs != 0 {
		n += 1 + sovE2E(uint64(m.TrustingPeriodSecs))
	}
	if m.MaxClockDriftSecs != 0 {
		n += 1 + sovE2E(uint64(m.MaxClockDriftSecs))
	}
	l = len(m.IbcAddress)
	if l > 0 {
		n += 1 + l + sovE2E(uint64(l))
	}
	if m.TrustedSyncCommittee != nil {
		l = m.TrustedSyncCommittee.Size()
		n += 1 + l + sovE2E(uint64(l))
	}
	l = len(m.TrustedCurrentSyncCommittee)
	if l > 0 {
		n += 1 + l + sovE2E(uint64(l))
	}
	l = len(m.TrustedNextSyncCommittee)
	if l > 0 {
		n += 2 + l + sovE2E(uint64(l))
	}
	if m.TrustedTimestampSecs != 0 {
		n += 2 + sovE2E(uint64(m.TrustedTimestampSecs))
	}
	if m.ConsensusUpdate != nil {
		l = m.ConsensusUpdate.Size()
		n += 2 + l + sovE2E(uint64(l))
	}
	if m.ExecutionUpdate != nil {
		l = m.ExecutionUpdate.Size()
		n += 2 + l + sovE2E(uint64(l))
	}
	if m.AccountUpdate != nil {
		l = m.AccountUpdate.Size()
		n += 2 + l + sovE2E(uint64(l))
	}
	if m.HeaderTimestampSecs != 0 {
		n += 2 + sovE2E(uint64(m.HeaderTimestampSecs))
	}
	if m.NowSecs != 0 {
		n += 2 + sovE2E(uint64(m.NowSecs))
	}
	l = len(m.IbcCommitmentsSlot)
	if l > 0 {
		n += 2 + l + sovE2E(uint64(l))
	}
	l = len(m.MembershipPath)
	if l > 0 {
		n += 2 + l + sovE2E(uint64(l))
	}
	l = len(m.MembershipValue)
	if l > 0 {
		n += 2 + l + sovE2E(uint64(l))
	}
	l = len(m.MembershipProof)
	if l > 0 {
		n += 2 + l + sovE2E(uint64(l))
	}
	return n
}

func (m *VerifyUpdateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CurrentSyncCommittee)
	if l > 0 {
		n += 1 + l + sovE2E(uint64(l))
	}
	l = len(m.NextSyncCommittee)
	if l > 0 {
		n += 1 + l + sovE2E(uint64(l))
	}
	return n
}

func sovE2E(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozE2E(x uint64) (n int) {
	return sovE2E(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VerifyUpdateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowE2E
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyUpdateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyUpdateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncCommitteeSize", wireType)
			}
			m.SyncCommitteeSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SyncCommitteeSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisValidatorsRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisValidatorsRoot = append(m.GenesisValidatorsRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.GenesisValidatorsRoot == nil {
				m.GenesisValidatorsRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSyncCommitteeParticipants", wireType)
			}
			m.MinSyncCommitteeParticipants = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinSyncCommitteeParticipants |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisTime", wireType)
			}
			m.GenesisTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForkParameters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ForkParameters == nil {
				m.ForkParameters = &types.ForkParameters{}
			}
			if err := m.ForkParameters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondsPerSlot", wireType)
			}
			m.SecondsPerSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecondsPerSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotsPerEpoch", wireType)
			}
			m.SlotsPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotsPerEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochsPerSyncCommitteePeriod", wireType)
			}
			m.EpochsPerSyncCommitteePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochsPerSyncCommitteePeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevelNumerator", wireType)
			}
			m.TrustLevelNumerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustLevelNumerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevelDenominator", wireType)
			}
			m.TrustLevelDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustLevelDenominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriodSecs", wireType)
			}
			m.TrustingPeriodSecs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustingPeriodSecs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClockDriftSecs", wireType)
			}
			m.MaxClockDriftSecs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClockDriftSecs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcAddress = append(m.IbcAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcAddress == nil {
				m.IbcAddress = []byte{}
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedSyncCommittee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustedSyncCommittee == nil {
				m.TrustedSyncCommittee = &types.TrustedSyncCommittee{}
			}
			if err := m.TrustedSyncCommittee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedCurrentSyncCommittee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrustedCurrentSyncCommittee = append(m.TrustedCurrentSyncCommittee[:0], dAtA[iNdEx:postIndex]...)
			if m.TrustedCurrentSyncCommittee == nil {
				m.TrustedCurrentSyncCommittee = []byte{}
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedNextSyncCommittee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrustedNextSyncCommittee = append(m.TrustedNextSyncCommittee[:0], dAtA[iNdEx:postIndex]...)
			if m.TrustedNextSyncCommittee == nil {
				m.TrustedNextSyncCommittee = []byte{}
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedTimestampSecs", wireType)
			}
			m.TrustedTimestampSecs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustedTimestampSecs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusUpdate == nil {
				m.ConsensusUpdate = &types.ConsensusUpdate{}
			}
			if err := m.ConsensusUpdate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExecutionUpdate == nil {
				m.ExecutionUpdate = &types.ExecutionUpdate{}
			}
			if err := m.ExecutionUpdate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountUpdate == nil {
				m.AccountUpdate = &types.AccountUpdate{}
			}
			if err := m.AccountUpdate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeaderTimestampSecs", wireType)
			}
			m.HeaderTimestampSecs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeaderTimestampSecs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NowSecs", wireType)
			}
			m.NowSecs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NowSecs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcCommitmentsSlot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcCommitmentsSlot = append(m.IbcCommitmentsSlot[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcCommitmentsSlot == nil {
				m.IbcCommitmentsSlot = []byte{}
			}
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembershipPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembershipPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembershipValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembershipValue = append(m.MembershipValue[:0], dAtA[iNdEx:postIndex]...)
			if m.MembershipValue == nil {
				m.MembershipValue = []byte{}
			}
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembershipProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembershipProof = append(m.MembershipProof[:0], dAtA[iNdEx:postIndex]...)
			if m.MembershipProof == nil {
				m.MembershipProof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipE2E(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthE2E
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifyUpdateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowE2E
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyUpdateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyUpdateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentSyncCommittee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentSyncCommittee = append(m.CurrentSyncCommittee[:0], dAtA[iNdEx:postIndex]...)
			if m.CurrentSyncCommittee == nil {
				m.CurrentSyncCommittee = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextSyncCommittee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthE2E
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthE2E
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextSyncCommittee = append(m.NextSyncCommittee[:0], dAtA[iNdEx:postIndex]...)
			if m.NextSyncCommittee == nil {
				m.NextSyncCommittee = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipE2E(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthE2E
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipE2E(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowE2E
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowE2E
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthE2E
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupE2E
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthE2E
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthE2E        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowE2E          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupE2E = fmt.Errorf("proto: unexpected end of group")
)
